---
title: "SumarizedExperiment y iSEE"
author: "Eduardo Arrieta"
date: "27/2/2021"
output: html_document
---
# Código previo
```{r message=FALSE, echo=FALSE}
## Lets build our first SummarizedExperiment object
library("SummarizedExperiment")
## ?SummarizedExperiment
```

```{r message=FALSE, echo=FALSE}
## De los ejemplos en la ayuda oficial

## Creamos los datos para nuestro objeto de tipo SummarizedExperiment
## para 200 genes a lo largo de 6 muestras
nrows <- 200
ncols <- 6
## Números al azar de cuentas
set.seed(20210223)
counts <- matrix(runif(nrows * ncols, 1, 1e4), nrows)
## Información de nuestros genes
rowRanges <- GRanges(
  rep(c("chr1", "chr2"), c(50, 150)),
  IRanges(floor(runif(200, 1e5, 1e6)), width = 100),
  strand = sample(c("+", "-"), 200, TRUE),
  feature_id = sprintf("ID%03d", 1:200)
)
names(rowRanges) <- paste0("gene_", seq_len(length(rowRanges)))
## Información de nuestras muestras
colData <- DataFrame(
  Treatment = rep(c("ChIP", "Input"), 3),
  row.names = LETTERS[1:6]
)
## Juntamos ahora toda la información en un solo objeto de R
rse <- SummarizedExperiment(
  # Las tablas de ASSAY deben ser de las mismas dimensiones
  assays = SimpleList(counts = counts),
  rowRanges = rowRanges,
  colData = colData
)
```

```{r}
rse
```


## Explica que sucede en las siguientes líneas de código de R.
```{r}
## Comando 1
# Imprime los primeros dos genes del objeto a lo largo de todas la muestras
rse[1:2, ]
## Comando 2
# Imprimirá todos los genes en las muestras A, D Y F
rse[, c("A", "D", "F")]
```

## Creación de imagenes con iSEE a partir de un set de datos

```{r}
# Almacenado en colData Names
rse$Treatment
```


```{r eval=FALSE}
## Explora el objeto rse de forma interactiva
library("iSEE")
iSEE::iSEE(rse)

# Ejercicio ISEE
## Descarguemos unos datos de spatialLIBD
sce_layer <- spatialLIBD::fetch_data("sce_layer")
iSEE::iSEE(sce_layer)

rowRanges(sce_layer[c('ENSG00000168314', 'ENSG00000183036', 'ENSG00000197971'),])$gene_name
# [1] "MOBP" "PCP4" "MBP"

# Generación de un subset
sce_short_3 <- sce_layer[c('ENSG00000168314', 'ENSG00000183036', 'ENSG00000197971'),]
iSEE::iSEE(sce_short_3)
sce_short_3
iSEE::iSEE(sce_layer[c('ENSG00000168314', 'ENSG00000183036', 'ENSG00000197971'),])
```

## Imágenes generadas
[PCA](https://github.com/eduardo-arrieta/rnaseq_2021_notas/blob/master/figuras/ReducedDimensionPlot1.pdf)
