---
title: 'Ejercicio Grupal: recount3'
author: "Eduardo Arrieta"
date: "27/2/2021"
output: html_document
---
```{r message=FALSE, echo=FALSE}
## Load recount3 R package
library("recount3")
```

```{r message=FALSE, echo=FALSE}
## Revisemos todos los proyectos con datos de humano en recount3
human_projects <- available_projects()
## Encuentra tu proyecto de interés. Aquí usaremos
## SRP009615 de ejemplo
proj_info <- subset(
  human_projects,
  project == "SRP009615" & project_type == "data_sources"
)
## Crea un objetio de tipo RangedSummarizedExperiment (RSE)
## con la información a nivel de genes
rse_gene_SRP009615 <- create_rse(proj_info)
```

```{r message=FALSE, echo=FALSE}
## Convirtamos las cuentas por nucleotido a cuentas por lectura
## usando compute_read_counts().
## Para otras transformaciones como RPKM y TPM, revisa transform_counts().
assay(rse_gene_SRP009615, "counts") <- compute_read_counts(rse_gene_SRP009615)

## Para este estudio en específico, hagamos más fácil de usar la
## información del experimento
rse_gene_SRP009615 <- expand_sra_attributes(rse_gene_SRP009615)
```

##Código previo
```{r}
rse_gene_SRP009615
```

Uso de iSEE para reproducir una imagen
```{r eval=FALSE}
# Ploeo de expresión
iSEE::iSEE(rse_gene_SRP009615)
# La imagen se guardó en figuras
```
Imagen en 
[Expresion](https://github.com/eduardo-arrieta/rnaseq_2021_notas/blob/master/figuras/168314_17expresion.pdf)
